package com.kwiby.musik.data.daos.playlists

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import com.kwiby.musik.data.data_classes.AudioFile
import com.kwiby.musik.data.data_classes.Playlist
import com.kwiby.musik.data.data_classes.PlaylistDetails
import com.kwiby.musik.data.data_classes.PlaylistEntry
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaylistDao {
	// --===-- Playlists --===--
	@Insert
	suspend fun createPlaylist(playlist: Playlist): Long // Returns an autogenerated playlistId

	@Delete
	suspend fun deletePlaylist(playlist: Playlist)

	@Update
	suspend fun updatePlaylists(playlists: List<Playlist>) // PRIVATE

	@Query("SELECT COUNT(*) FROM playlists")
	suspend fun getPlaylistCount(): Int // PRIVATE

	@Query("SELECT * FROM playlists ORDER BY orderPos ASC")
	fun getAllPlaylists(): Flow<List<Playlist>>

	@Transaction
	suspend fun reorderPlaylists(newOrder: List<Playlist>) {
		val updatedPlaylist = newOrder.mapIndexed { index, playlist ->
			playlist.copy(orderPos = index)
		}
		updatePlaylists(updatedPlaylist)
	}

	@Transaction
	@Query("SELECT * FROM playlists WHERE id = :playlistId")
	fun getPlaylistDetails(playlistId: Long): Flow<PlaylistDetails>

	@Transaction
	@Query("SELECT * FROM playlists")
	fun getAllPlaylistDetails(): Flow<List<PlaylistDetails>>


	// --===--  Playlist Entries --===--
	@Insert(onConflict = OnConflictStrategy.IGNORE)
	suspend fun insertPlaylistEntry(playlistEntry: PlaylistEntry) // PRIVATE

	@Update
	suspend fun updatePlaylistEntries(entries: List<PlaylistEntry>) // PRIVATE

	@Query("SELECT * FROM playlist_entries WHERE playlistId = :playlistId ORDER BY orderPos ASC")
	suspend fun getPlaylistEntries(playlistId: Long): List<PlaylistEntry> // PRIVATE

	@Query("SELECT COUNT(*) FROM playlist_entries WHERE playlistId = :playlistId")
	suspend fun getPlaylistEntryCount(playlistId: Long): Int

	@Query("DELETE FROM playlist_entries WHERE playlistId = :playlistId AND songId = :songId")
	suspend fun deletePlaylistEntry(playlistId: Long, songId: Long) // PRIVATE

	@Query("""
		SELECT music_list.* FROM music_list
		INNER JOIN playlist_entries ON music_list.id = playlist_entries.songId
		WHERE playlist_entries.playlistId = :playlistId
		ORDER BY playlist_entries.orderPos ASC
	""")
	fun getOrderedSongsInPlaylist(playlistId: Long): Flow<List<AudioFile>>


	@Transaction
	suspend fun addSongToPlaylist(playlistId: Long, songId: Long) {
		val nextPos = getPlaylistEntryCount(playlistId)
		insertPlaylistEntry(
			PlaylistEntry(
				playlistId = playlistId,
				songId = songId,
				orderPos = nextPos
			)
		)
	}

	@Transaction
	suspend fun removeSongFromPlaylist(playlistId: Long, songId: Long) {
		deletePlaylistEntry(playlistId, songId)
		val remaining = getPlaylistEntries(playlistId)
		val reindexed = remaining.mapIndexed { index, entry ->
			entry.copy(orderPos = index)
		}
		updatePlaylistEntries(reindexed)
	}

	@Transaction
	suspend fun reorderPlaylistEntries(playlistId: Long, newSongOrder: List<Long>) {
		val updatedEntries = newSongOrder.mapIndexed { index, songId ->
			PlaylistEntry(
				playlistId = playlistId,
				songId = songId,
				orderPos = index
			)
		}
		updatePlaylistEntries(updatedEntries)
	}
}